### ISSUE TITLE
how can i pass multiple attributes to the task?

### ISSUE THREAD

**Issue by guilopes22** [sashman/absinthe_gen#2]
i'm trying to generate the files with multiple attributes in this way:

`mix absinthe.gen.scaffold my_context my_type [my_field:string, my_other_field:string]`

but this isn't working. i'm getting this error: `zsh: bad pattern: [my_field:string,`

**Comment by sashman** [comment]
Remove the `[]` and you also don't need the `,`. I will update the README to make it more clear.

**Comment by sashman** [comment]
@guilopes22 did the above work for you? can this be closed?
